# Generated by Django 4.2.13 on 2024-05-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('weather', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Seco'), ('mild', 'Templado'), ('continental', 'Continental'), ('cool', 'Frios'), ('anyone', 'Cualquiera')], default='anyone', max_length=15)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
