# Generated by Django 4.2.13 on 2024-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden_World', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name_plural': 'crops'},
        ),
        migrations.AddField(
            model_name='crop',
            name='dificulty',
            field=models.CharField(choices=[('begginer', 'Principiante'), ('medium', 'Medio'), ('hard', 'Dificil')], default='begginer', max_length=10),
        ),
        migrations.AddField(
            model_name='crop',
            name='illumination',
            field=models.CharField(choices=[('sun', 'Sol'), ('half_shadow', 'Media sombra'), ('shadow', 'Sombra')], default='sun', max_length=12),
        ),
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('anyone', 'Cualquiera'), ('spring', 'Primavera'), ('summer', 'Verano'), ('autumn', 'otoño'), ('winter', 'Invierno')], default='anyone', max_length=10),
        ),
        migrations.AddField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('vegetables', 'Hortalizas'), ('flowers', 'Flores'), ('shadow', 'Sombra')], default='vegetables', max_length=10),
        ),
        migrations.AlterField(
            model_name='crop',
            name='weather',
            field=models.CharField(choices=[('anyone', 'Cualquiera'), ('tropical', 'Tropical'), ('dry', 'Seco'), ('mild', 'Templado'), ('continental', 'Continental'), ('cool', 'Frios')], default='anyone', max_length=15),
        ),
    ]
