# Generated by Django 4.2.13 on 2024-05-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden_World', '0002_alter_crop_options_crop_dificulty_crop_illumination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('vegetables', 'Hortalizas'), ('flowers', 'Flores'), ('aromatics', 'Aromaticas')], default='vegetables', max_length=10),
        ),
    ]
