# Generated by Django 4.2.13 on 2024-05-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garden_World', '0003_alter_crop_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'crop', 'verbose_name_plural': 'crops'},
        ),
    ]
