# Generated by Django 4.2.13 on 2024-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garden_World', '0005_crop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='owner',
        ),
    ]
